# Generated by Django 5.2.5 on 2025-08-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalMedicineFinderapp', '0002_medicine_pharmacy_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacies'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicines'),
        ),
    ]
