# Generated by Django 5.2.5 on 2025-08-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalMedicineFinderapp', '0004_whishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserregister',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
