# Generated by Django 5.2.5 on 2025-08-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalMedicineFinderapp', '0005_customuserregister_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserregister',
            name='city',
        ),
    ]
